window.manualSeedData = {
  categories: {
    all: "전체",
    cmcs: "CM/CS프로젝트",
    performance: "성과확산",
    equipment: "기자재/시설",
    etc: "일반행정",
    personalAdmin: "개인행정",
  },

  legacyCategoryMap: {
    operation: "etc",
    sales: "cmcs",
    finance: "etc",
    hr: "etc",
    it: "equipment",
  },

  owners: ["SW교육원", "AI교육원", "AI/SW교육지원팀"],

  manuals: [
    {
      id: "monthly-close",
      title: "월말 정산 마감 절차",
      category: "etc",
      owner: "AI/SW교육지원팀",
      updatedAt: "2026-04-15",
      status: "정상",
      summary: "매월 마지막 영업일 기준 매출, 비용, 미수금을 확인하고 마감 보고서를 작성합니다.",
      steps: [
        "거래처별 세금계산서 발행 여부를 확인합니다.",
        "미입금 내역을 정리하고 담당자에게 확인 요청을 보냅니다.",
        "정산 파일의 합계와 회계 시스템 금액을 대조합니다.",
        "팀장 검토 후 월말 마감 보고서를 공유합니다.",
      ],
      reference: "사내 드라이브 > 재무 > 월말정산 템플릿.xlsx",
    },
    {
      id: "new-client",
      title: "신규 거래처 등록",
      category: "cmcs",
      owner: "AI/SW교육지원팀",
      updatedAt: "2026-03-28",
      status: "정상",
      summary: "계약 전 사업자 정보, 담당자 연락처, 결제 조건을 확인해 내부 시스템에 등록합니다.",
      steps: [
        "사업자등록증과 통장 사본을 수령합니다.",
        "거래처 중복 등록 여부를 검색합니다.",
        "결제 조건과 세금계산서 수신 이메일을 입력합니다.",
        "승인 완료 후 영업 담당자에게 등록 완료를 알립니다.",
      ],
      reference: "ERP > 거래처 관리 > 신규 등록",
    },
    {
      id: "vacation-request",
      title: "연차 및 반차 신청",
      category: "etc",
      owner: "SW교육원",
      updatedAt: "2026-02-10",
      status: "정상",
      summary: "근태 시스템에서 휴가 일정을 등록하고 팀 승인 상태를 확인합니다.",
      steps: [
        "희망 휴가일을 팀 캘린더에서 먼저 확인합니다.",
        "근태 시스템에서 연차 또는 반차 유형을 선택합니다.",
        "업무 인수인계 메모를 작성합니다.",
        "승인 상태가 반려일 경우 사유를 확인하고 재신청합니다.",
      ],
      reference: "근태 시스템 > 휴가 신청",
    },
    {
      id: "device-request",
      title: "업무 장비 요청",
      category: "equipment",
      owner: "AI/SW교육지원팀",
      updatedAt: "2026-01-22",
      status: "정상",
      summary: "노트북, 모니터, 계정 권한 등 업무 장비와 접근 권한을 요청하는 절차입니다.",
      steps: [
        "요청 목적과 필요한 사용 기간을 작성합니다.",
        "팀장 승인 후 IT 헬프데스크 티켓을 등록합니다.",
        "장비 수령 시 자산번호와 상태를 확인합니다.",
        "퇴사 또는 부서 이동 시 반납 일정을 등록합니다.",
      ],
      reference: "IT 헬프데스크 > 자산/권한 요청",
    },
    {
      id: "daily-report",
      title: "일일 운영 보고",
      category: "performance",
      owner: "AI교육원",
      updatedAt: "2026-04-01",
      status: "정상",
      summary: "당일 처리 건수, 이슈, 익일 확인 사항을 정리해 운영 채널에 공유합니다.",
      steps: [
        "오전 기준 미처리 건과 긴급 건을 확인합니다.",
        "업무 종료 전 처리 완료 건과 보류 사유를 기록합니다.",
        "반복 이슈는 원인과 개선 요청 항목으로 분리합니다.",
        "공유 양식에 맞춰 운영 채널에 게시합니다.",
      ],
      reference: "사내 위키 > 운영팀 > 일일보고 양식",
    },
  ],
};
